#!/usr/bin/env bash
# scripts/build-all.sh
# プラットフォーム全体を1つの dist/ にビルドする
#
# 出力構造:
#   dist/               ← portal (ゲーム一覧・マニフェスト・SW)
#   dist/games/[id]/    ← 各ゲーム
#
# 使い方 (ローカル):
#   bash scripts/build-all.sh              # 全ゲーム
#   bash scripts/build-all.sh ntiktaktoe   # 特定ゲームのみ (portal は常にビルド)
#
# CI 環境変数 (GitHub Actions からセットされる):
#   BUILD_GAME_IDS    - ビルド対象ゲームID の JSON配列 (例: ["ntiktaktoe","game2"])
#                       空配列 [] の場合は全ゲームをビルド
#   FORCE_FULL_BUILD  - "true" で全ゲームを強制ビルド (scripts/package.json 変更時)
#   PORTAL_CHANGED    - "true" の場合でも portal は常にビルドするため実質未使用

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
TARGET_GAME="${1:-}"

echo "=== Platform Build Start ==="
echo "Output: $DIST_DIR"

# ── 1. 出力ディレクトリを初期化 ──────────────────────────────────────
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# ── 2. portal をビルド ────────────────────────────────────────────────
# portal は常にビルドする (全ゲームへのリンクを含むため)
echo ""
echo "→ Building portal..."
cd "$ROOT_DIR/portal"
npm install --prefer-offline --silent
npm run build
cp -r "$ROOT_DIR/portal/dist/." "$DIST_DIR/"
echo "  ✅ portal → dist/"

# ── 3. 各ゲームをビルド (/games/[id]/ に展開) ────────────────────────
# 環境変数による差分ビルド制御:
#   FORCE_FULL_BUILD=true  → 全ゲームビルド
#   BUILD_GAME_IDS=["id1"] → JSON配列で指定されたゲームのみビルド
#   TARGET_GAME=id        → 後方互換: 特定ゲームのみ (旧CLI引数)
FORCE_FULL_BUILD="${FORCE_FULL_BUILD:-false}"
BUILD_GAME_IDS="${BUILD_GAME_IDS:-[]}"

# JSON配列にゲームIDが含まれるか判定 (jq が使える前提)
_should_build_game() {
  local game_id="$1"
  if [ "$FORCE_FULL_BUILD" = "true" ]; then
    return 0  # 全ビルド
  fi
  if [ -n "$TARGET_GAME" ]; then
    [ "$game_id" = "$TARGET_GAME" ] && return 0 || return 1
  fi
  # BUILD_GAME_IDS が空配列なら全ビルド、そうでなければ含まれるか確認
  local count
  count=$(echo "$BUILD_GAME_IDS" | jq '. | length' 2>/dev/null || echo 0)
  if [ "$count" = "0" ]; then
    return 0  # 全ビルド (ローカル実行時など)
  fi
  echo "$BUILD_GAME_IDS" | jq -e --arg id "$game_id" '. | index($id) != null' > /dev/null 2>&1
}

GAMES_DIR="$ROOT_DIR/games"
if [ ! -d "$GAMES_DIR" ]; then
  echo ""
  echo "  ⚠  games/ ディレクトリが存在しないためスキップ (モノレポ移行前)"
else
  for GAME_DIR in "$GAMES_DIR"/*/; do
    [ -d "$GAME_DIR" ] || continue
    [ -f "$GAME_DIR/package.json" ] || continue

    GAME_ID="$(basename "$GAME_DIR")"
    [ "$GAME_ID" = "_template" ] && continue

    if ! _should_build_game "$GAME_ID"; then
      echo ""
      echo "  ⏭  $GAME_ID: 変更なし、スキップ"
      continue
    fi

    echo ""
    echo "→ Building game: $GAME_ID (/games/$GAME_ID/)..."
    cd "$GAME_DIR"
    npm install --prefer-offline --silent
    npm run build

    DEST="$DIST_DIR/games/$GAME_ID"
    mkdir -p "$DEST"
    cp -r "dist/." "$DEST/"
    echo "  ✅ $GAME_ID → dist/games/$GAME_ID/"
  done
fi

# ── 4. Cloudflare Pages 用のキャッシュヘッダーを生成 ──────────────────
echo ""
echo "→ Generating _headers for Cloudflare Pages..."
cat > "$DIST_DIR/_headers" << 'HEADERS'
# Hashed assets (JS/CSS with content hash) — immutable cache
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/games/*/assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML — always revalidate
/*.html
  Cache-Control: public, max-age=0, must-revalidate
/games/*/*.html
  Cache-Control: public, max-age=0, must-revalidate

# Service Worker — never cache
/sw.js
  Cache-Control: no-store
/service-worker.js
  Cache-Control: no-store

# Manifest — short cache
/manifest.webmanifest
  Cache-Control: public, max-age=3600
/manifest.json
  Cache-Control: public, max-age=3600

# SPA fallback
/games/*
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
HEADERS
echo "  ✅ _headers 生成完了"

# ── 5. _redirects (SPA フォールバック) ──────────────────────────────
echo ""
echo "→ Generating _redirects..."
# 各ゲームのパスが直リンクされても index.html を返す
REDIRECTS="$DIST_DIR/_redirects"
echo "# Generated by build-all.sh" > "$REDIRECTS"
if [ -d "$GAMES_DIR" ]; then
  for GAME_DIR in "$GAMES_DIR"/*/; do
    GAME_ID="$(basename "$GAME_DIR")"
    [ "$GAME_ID" = "_template" ] && continue
    [ -d "$GAME_DIR" ] || continue
    echo "/games/$GAME_ID/*  /games/$GAME_ID/index.html  200" >> "$REDIRECTS"
  done
fi
echo "  ✅ _redirects 生成完了"

# ── 完了 ──────────────────────────────────────────────────────────────
echo ""
echo "=== Build Complete ==="
echo "Total size: $(du -sh "$DIST_DIR" | cut -f1)"
echo ""
echo "dist/ 構造:"
find "$DIST_DIR" -maxdepth 3 -type d | sed "s|$DIST_DIR||" | sort
