#!/usr/bin/env bash
# scripts/build-all.sh
# プラットフォーム全体を1つの dist/ にビルドする
#
# 出力構造:
#   dist/               ← portal (ゲーム一覧・マニフェスト・SW)
#   dist/games/[id]/    ← 各ゲーム
#
# 使い方:
#   bash scripts/build-all.sh            # 全ゲーム
#   bash scripts/build-all.sh ntiktaktoe # 特定ゲームのみ (portal は常にビルド)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
TARGET_GAME="${1:-}"

echo "=== Platform Build Start ==="
echo "Output: $DIST_DIR"

# ── 1. 出力ディレクトリを初期化 ──────────────────────────────────────
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# ── 2. portal をビルド (root に展開) ─────────────────────────────────
echo ""
echo "→ Building portal..."
cd "$ROOT_DIR/portal"
npm install --prefer-offline --silent
npm run build
# Astro は dist/ に出力する
cp -r "$ROOT_DIR/portal/dist/." "$DIST_DIR/"
echo "  ✅ portal → dist/"

# ── 3. 各ゲームをビルド (/games/[id]/ に展開) ────────────────────────
GAMES_DIR="$ROOT_DIR/games"
if [ ! -d "$GAMES_DIR" ]; then
  echo ""
  echo "  ⚠  games/ ディレクトリが存在しないためスキップ (モノレポ移行前)"
  # 移行前: ルートの src/ をそのままビルドして dist/games/ntiktaktoe/ に配置
  echo "→ Building root game (pre-migration)..."
  cd "$ROOT_DIR"
  if [ -f "package.json" ] && grep -q '"build"' package.json; then
    npm install --prefer-offline --silent
    npm run build
    mkdir -p "$DIST_DIR/games/ntiktaktoe"
    cp -r "$ROOT_DIR/dist_tmp/." "$DIST_DIR/games/ntiktaktoe/" 2>/dev/null || true
  fi
else
  for GAME_DIR in "$GAMES_DIR"/*/; do
    [ -d "$GAME_DIR" ] || continue
    [ -f "$GAME_DIR/package.json" ] || continue

    GAME_ID="$(basename "$GAME_DIR")"

    # _template はビルドしない
    [ "$GAME_ID" = "_template" ] && continue

    # 特定ゲームのみビルドするオプション
    if [ -n "$TARGET_GAME" ] && [ "$GAME_ID" != "$TARGET_GAME" ]; then
      continue
    fi

    echo ""
    echo "→ Building game: $GAME_ID (/games/$GAME_ID/)..."
    cd "$GAME_DIR"
    npm install --prefer-offline --silent
    npm run build

    DEST="$DIST_DIR/games/$GAME_ID"
    mkdir -p "$DEST"
    cp -r "dist/." "$DEST/"
    echo "  ✅ $GAME_ID → dist/games/$GAME_ID/"
  done
fi

# ── 4. Cloudflare Pages 用のキャッシュヘッダーを生成 ──────────────────
echo ""
echo "→ Generating _headers for Cloudflare Pages..."
cat > "$DIST_DIR/_headers" << 'HEADERS'
# Hashed assets (JS/CSS with content hash) — immutable cache
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/games/*/assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML — always revalidate
/*.html
  Cache-Control: public, max-age=0, must-revalidate
/games/*/*.html
  Cache-Control: public, max-age=0, must-revalidate

# Service Worker — never cache
/sw.js
  Cache-Control: no-store
/service-worker.js
  Cache-Control: no-store

# Manifest — short cache
/manifest.webmanifest
  Cache-Control: public, max-age=3600
/manifest.json
  Cache-Control: public, max-age=3600

# SPA fallback
/games/*
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
HEADERS
echo "  ✅ _headers 生成完了"

# ── 5. _redirects (SPA フォールバック) ──────────────────────────────
echo ""
echo "→ Generating _redirects..."
# 各ゲームのパスが直リンクされても index.html を返す
REDIRECTS="$DIST_DIR/_redirects"
echo "# Generated by build-all.sh" > "$REDIRECTS"
if [ -d "$GAMES_DIR" ]; then
  for GAME_DIR in "$GAMES_DIR"/*/; do
    GAME_ID="$(basename "$GAME_DIR")"
    [ "$GAME_ID" = "_template" ] && continue
    [ -d "$GAME_DIR" ] || continue
    echo "/games/$GAME_ID/*  /games/$GAME_ID/index.html  200" >> "$REDIRECTS"
  done
fi
echo "  ✅ _redirects 生成完了"

# ── 完了 ──────────────────────────────────────────────────────────────
echo ""
echo "=== Build Complete ==="
echo "Total size: $(du -sh "$DIST_DIR" | cut -f1)"
echo ""
echo "dist/ 構造:"
find "$DIST_DIR" -maxdepth 3 -type d | sed "s|$DIST_DIR||" | sort
